### ISSUE TITLE
npm i ....

### ISSUE THREAD

**Issue by Mmas9270** [epam/mriviewer#154] opened 2023-05-29 11:14 UTC
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by DanilRostov** [comment] 2023-07-07 00:07
Dear @Mmas9270, thaks for raising an issue.

Could you prive the steps to reproduce this issue? 
Please descrive your environment and provide as much details as possible?
Also, do you use any proxy settings for your network or NPM?

**Comment by DanilRostov** [comment] 2023-12-12 02:30
Closing this issue since we haven't received ant response. `npm i` should work find right now.

**Closed by DanilRostov** 2023-12-12 02:30 UTC
Labels: under clarification
